# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=Five5Guys?
ENV POSTGRES_DB=taskdb

# Expose the PostgreSQL port
EXPOSE 5432

# Set up a volume for persistent data
VOLUME /var/lib/postgresql/data