version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Five5Guys?
      POSTGRES_DB: taskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  todolist:
    image: 148.60.225.81:5000/iai3_01_malo_back-image-01:0.1
    ports:
      - "80:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Five5Guys?

volumes:
  postgres_data:
